server:
  port: 8080

spring:
  datasource:
    # These placeholders will be read from environment variables on your hosting platform
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update # For production, this is often set to 'validate'